project:
  type: book
  output-dir: docs

book:
  title: "Programación defensiva con ggplot2"
  author: "Evelia Coss"
  date: "10/23/2024"
  page-navigation: true
  chapters:
    - index.qmd
    - Parte1.qmd
    - Parte2.qmd
    - Parte3.qmd
    - Parte4.qmd
    - Parte5.qmd
  # Information
  repo-url: https://github.com/EveliaCoss/ViernesBioinfo2024_parte2/ # link de Github
  sharing: [twitter, facebook, linkedin]
  favicon: "ViernesBioinfo_logo.png" # icono de la pagina en pestana

format:
  html:
    toc-depth: 4
    number-depth: 3
  # Boton para cambiar tema de oscuro a claro
    theme:
      light: cosmo
      dark: darkly
    code-fold: show # Ocultar codigo
    code-copy: true # Copy button
    freeze: false  # Desactivar congelamiento

editor: visual

