# Proyecto final {.unnumbered}

::: {.callout-note icon="false"}
## Instrucciones:

Trabajo individual o en equipo (3 personas):

1.  Seleccionar uno de los [Datasets](https://stat.ethz.ch/R-manual/R-devel/library/datasets/html/00Index.html) precargados en R o los que son propios de los [paquetes](https://vincentarelbundock.github.io/Rdatasets/articles/data.html).

2.  Analiza los datos y genera 3 preguntas que puedas contestar con las variables que tienes.

3.  Genera un script completo que nos conteste las preguntas realizadas y nos de graficas de cada uno.

**NOTA:** No olvides agregar la programacion defensiva y un poco de todo lo visto en clase (Manipulacion de datos, funciones, BUENAS PRACTICAS, ggplot2 o Complexheatmap).

**NOTA:** No olvides que es muy importante documentar todo.

**Entregables:**

-   Crear un reporte o un libro en Rmarkdown o [Quarto](https://quarto.org/docs/output-formats/html-basics.html) (entregarlo el 5 de Diciembre antes de las 11 pm hora Ciudad de Mexico).

-   Genera una exposicion breve (empleando [Xaringan](https://bookdown.org/yihui/rmarkdown/xaringan.html) o [Quarto](https://quarto.org/docs/presentations/) en R) de 15 min en total por equipo (practica el tiempo para que sea de provecho).

-   Sube todo a Github, el repositorio debe ser publico y debe contener tu reporte y presentacion. NO olvides poner tu nombre y la de tu equipo en el README.

-   Exposicion el **6 de diciembre**
:::
